java-bean-validation/README.md, java-bean-validation/pom.xml, java-bean-validation/src/main/java/com/canoo/dolphin/validation/AbstractPropertyValidator.java, java-bean-validation/src/main/java/com/canoo/dolphin/validation/AssertFalsePropertyValidator.java, java-bean-validation/src/main/java/com/canoo/dolphin/validation/AssertTruePropertyValidator.java, java-bean-validation/src/main/java/com/canoo/dolphin/validation/DecimalMaxPropertyValidatorForNumber.java, java-bean-validation/src/main/java/com/canoo/dolphin/validation/DecimalMinPropertyValidatorForNumber.java, java-bean-validation/src/main/java/com/canoo/dolphin/validation/NotNullPropertyValidator.java, java-bean-validation/src/main/java/com/canoo/dolphin/validation/NullPropertyValidator.java, java-bean-validation/src/main/resources/META-INF/mapping/validationMappingDolphinPlatform.xml, java-bean-validation/src/main/resources/META-INF/validation.xml, java-bean-validation/src/test/java/com/canoo/dolphin/validation/TestBean.java, java-bean-validation/src/test/java/com/canoo/dolphin/validation/ValidationTest.java, java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXBinderTest.java, java-core/src/main/java/com/canoo/dolphin/impl/MockedProperty.java, pom.xml
This module adds bean validation (JSR 303) support to the property API of the [Dolphin Platform](http://www.dolphin-platform.io). 
In this first pull request not all validation annotations that are part of JSR 303 are implemented. Additional implementation can be done by a second pull request. This Pull request is more about discussing the API and integration.
Properties and collections that are defined in Dolphin Platform models can be annotated by a Bean Validation constraint annotation. It's plan to support all the default JSR-303 annotations by simply adding this module.
The module based on a plugin mechanism for JSR-303 and therefore you only need to add the dependency to your project to use the validation support:
```xml
<dependency>
<groupId>com.canoo.dolphin-platform</groupId> …
```
=> JSR 303 based validation for Dolphin Platform

java-server/src/main/java/com/canoo/dolphin/server/event/DolphinEventBus.java, java-server/src/main/java/com/canoo/dolphin/server/event/Message.java, java-server/src/main/java/com/canoo/dolphin/server/event/MessageListener.java, java-server/src/main/java/com/canoo/dolphin/server/event/TaskExecutor.java, java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java, java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java, java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java, java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java, todo-example/client/src/main/java/com/canoo/dolphin/todo/client/ToDoItemCell.java, todo-example/client/src/main/java/com/canoo/dolphin/todo/client/ToDoViewBinder.java, todo-example/server/src/main/java/com/canoo/dolphin/todo/server/ToDoController.java
The event bus is type safe (by generics)
ToDo Example uses event Bus and syncs the state of ToDos
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/9)
=> Type safe Event Bus

java-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringContainerManager.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, java-server/src/main/java/com/canoo/dolphin/server/event/TaskExecutor.java, java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinContextTaskExecutor.java, java-server/src/main/java/com/canoo/dolphin/server/event/impl/TaskExecutorImpl.java, java-server/src/main/java/com/canoo/dolphin/server/event/impl/TaskTrigger.java
All classes / interfaces of the task executor are deprecated and can be removed in the next version.
The DolphinContext don't depend on the servant context / servlet API anymore that will make testing much easier.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/62)
=> task executor deprecated & some refactoring

java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java
Change order of listener registration, because the listeners are called in reverse order when the session is destroyed and DolphinSessionHandlerCleaner requires the DolphinContext to be intact.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/68)
=> Fix for memory leak

java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/CdiBeanFactory.java, java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/DolphinPlatformJavaeeBootstrap.java, java-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringBeanFactory.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinAccessException.java, java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java, todo-example/client/src/main/java/com/canoo/dolphin/todo/client/ToDoClient.java
This solves #138 by defining a lazy event bus that will throw an exception if the registration for a topic is called before DP Bootstrap is done.
This is a quick fix since we plan to solve #127 in near future. Here we can do the polishing for this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/145)
=> Lazy Event Bus

java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, java-client/src/main/java/com/canoo/dolphin/client/ClientContextFactory.java, java-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, todo-example/client/src/main/java/com/canoo/dolphin/todo/client/ToDoClient.java
If the serverURL is wrong the connect will run endless. This requests add a timeout (in the config) that will end in an regular exception if the server connection (and init command) can't be executed in the given time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/149)
=> Error on connection in client

documentation/dolphin-platform-documentation/src/docs/asciidoc/server-configuration.adoc, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/DolphinPlatformConfiguration.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ConfigurationFileLoader.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java
Since 0.8.5 we don't use the invalidation servlet anymore. With this change it will be deactivated by default but can be activated by using the dolphin.properties
If everything works well we can remove the servlet completely in a later version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/188)
=> Deactivate the invalidation servlet

platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestInMemoryConfiguration.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/ClientService.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/RequestService.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/ScopeModel.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/ScopeTestController.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/ScopeTestControllerTest.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/ScopesConfig.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/SessionService.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/SingletonService.java
Currently session (and request) scope is not supported in controller tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/206)
=> Bugfix for controller tests that support Session Scope in controllers

platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoClient.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java, platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/JavaFXConfiguration.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/DolphinPlatformHttpClientConnector.java, platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinPlatformHttpClientConnector.java
Currently in java client server URL is passed as String. Changed the String type to URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/254)
=> use URL instead of String in Java Client

documentation/dolphin-platform-documentation/src/docs/asciidoc/changelog.adoc
found minor tying marking the Deprecated as code and was confused with the additional headlines for upcooming versions. Suggest not to list them in the chanelog until they are released, added an UPCOMING for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/279)
=> minor things

remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/JsonCodec.java
The GSON encoder seems to work on fields and not on properties like the Groovy encoder does. Therefore we have to set the id explicitly on each command. The id-property is used in the JS-client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/337)
=> Store command-id explicitly

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/DolphinPlatformHttpClientConnector.java
This fixes a problem with empty HTTP headers that might be blocked by Apache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/366)
=> Fix for dirty HTTP header

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/MBeanRegistry.java
If Bean support is disabled the server do not tries to remove MBean anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/493)
=> Better MBeans handling

integration-common/src/main/java/com/canoo/dolphin/integration/property/PropertyTestConstants.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContextCommunicationHandler.java
bugfix for UTF-8 handling
unit test use UTF-8 characters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/541)
=> UTF-8  Encoding

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/event/LazyEventBusInvocationHandler.java
Fix to inject EventBus before DP bootstrap is done
Fix for https://github.com/canoo/dolphin-platform/issues/577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/583)
=> Fix to inject EventBus before DP bootstrap is done

platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/AbstractPropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/AssertFalsePropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/AssertTruePropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/DecimalMaxPropertyValidatorForNumber.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/DecimalMinPropertyValidatorForNumber.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/NotNullPropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/NullPropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/package-info.java, platform-extras/dolphin-platform-bean-validation/src/main/resources/META-INF/mapping/validationMappingDolphinPlatform.xml, platform-extras/dolphin-platform-bean-validation/src/test/java/com/canoo/dp/impl/validation/TestBean.java, platform-extras/dolphin-platform-bean-validation/src/test/java/com/canoo/dp/impl/validation/ValidationTest.java
All classes are moved to the default private API package of DP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/639)
=> Moving validation classes to private API package

platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/AbstractNumericDolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/AbstractNumericJavaFXBidirectionalBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/DefaultDolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/DefaultJavaFXBidirectionalBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/DefaultJavaFXBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/DoubleDolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/FloatDolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/IntegerDolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/dp/impl/client/javafx/LongDolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/BidirectionalConverter.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/Converter.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/binding/DefaultBidirectionalConverter.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/binding/DolphinBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/binding/JavaFXBidirectionalBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/binding/JavaFXBinder.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/binding/NumericJavaFXBidirectionaBinder.java, platform/dolphin-platform-remoting-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXBinderTest.java
Move Converter and BidirectionalConverter of JavaFX client API to com.canoo.platform.remoting.client.javafx
Fix typo in Converter JavaDoc
Remove BidirectionalConverter import from Converter
Fixes #635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/645)
=> Move Converter and BidirectionalConverter

platform-examples/process-monitor-sample/process-monitor-client-javafx/src/main/java/com/canoo/dolphin/samples/processmonitor/ProcessMonitorView.java, platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoView.java, platform-examples/web-deployment-example/web-deployment-client/src/main/java/com/canoo/dolphin/webdeployment/client/view/MyView.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/view/AbstractFXMLViewController.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/view/AbstractViewController.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/window/DolphinStage.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/window/DolphinWindow.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/window/DolphinWindowUtils.java
Refactoring of Code and respective Javadoc (see Issue #634)
All occurrences of `AbstractViewBinder` are changed to `AbstractViewController` and all occurrences of `AbstractFXMLViewBinder` are changed to `AbstractFXMLViewController` in both Code and javadoc documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/643)
=> Rename AbstractViewBinder to AbstractViewController (Issue #634)

.gitignore, platform/dolphin-platform-core/src/test/java/com/canoo/impl/platform/core/SimpleDolphinPlatformthreadFactoryTest.java
Hi @hendrikebbers , per your comments appended the new branch with eclipse specific .gitignore  (#675) and the required test  (#662). Also attaching code coverage screenshot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/683)
=> GitIgnore changes for Eclipse IDE & Test case for 662

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/context/DolphinContextTaskQueue.java
Added the exception cause in the log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/686)
=> #674 Concurrency error in task executor for Dolphin Platform: Cause not logged

platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/SizePropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/resources/META-INF/mapping/validationMappingDolphinPlatform.xml, platform-extras/dolphin-platform-bean-validation/src/test/java/com/canoo/dp/impl/validation/SizePropertyValidatorTest.java
Added the Size validator as described in #660 
I've considered that having a separate class for tests instead of one class with several is clearer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/687)
=> #660 add size validator

platform-examples/process-monitor-sample/process-monitor-client-javafx/src/main/java/com/canoo/dolphin/samples/processmonitor/ProcessMonitorView.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/FXWrapper.java
Moves class FXWrapper to package com.canoo.platform.remoting.client.javafx, 
because it was in the wrong package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/677)
=> Issue #633: Moves class FXWrapper to package

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/collections/ObservableArrayList.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/ObservableList.java, platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/collections/TestObservableArrayList.java
In particular, added the retainAll vararg overload, and the remove(int
from, int to) overload method.
It wasn't clear that the other additional methods were useful (they return other JavaFX classes which don't seem to have dolphin equivalents) or they were already implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/682)
=> Adding convenience methods from JavaFX's ObservableList

build.gradle
Pending: review all included paths in source code as there may be mistakes. For example, `com.canoo.platform.remoting.client.ControllerProxy` in project `dolphin-platform-remoting-client` expects a path resolved to `com/canoo/platform/remoting/client/doc-files/proxy.png` but is currently defined as `com/canoo/dolphin/client/doc-files/proxy.png`. This review is outside of the scope for this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/813)
=> Configure javadoc task to copy resources. Fixes #299

platform-extras/dolphin-platform-security-client/src/main/java/com/canoo/dp/impl/security/KeycloakSecurity.java, platform-extras/dolphin-platform-security-client/src/main/java/com/canoo/dp/impl/security/SecurityProvider.java, platform-extras/dolphin-platform-security-common/src/main/java/com/canoo/dp/impl/security/SecurityConfiguration.java, platform-extras/dolphin-platform-security-server/src/main/java/com/canoo/dp/impl/server/security/KeycloakConfiguration.java, platform-extras/dolphin-platform-security-server/src/main/java/com/canoo/dp/impl/server/security/KeycloakTokenServlet.java, platform-extras/dolphin-platform-security-server/src/main/java/com/canoo/dp/impl/server/security/LoginServlet.java, platform-extras/dolphin-platform-security-server/src/main/java/com/canoo/dp/impl/server/security/SecurityModule.java, platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/http/HttpCallExecutorImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/http/HttpCallRequestBuilderImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/http/HttpCallResponseBuilderImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/http/HttpClientImpl.java, platform/dolphin-platform-client/src/test/java/com/canoo/dp/impl/platform/client/http/HttpClientTests.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/http/ConnectionUtils.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/http/HttpClientConnection.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/http/HttpHeaderConstants.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/http/HttpHeaderImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/platform/core/functional/ExecutablePromise.java
Provides a login endpoint on the server (servlet based) in the security module.
The endpoint is a proxy to the Keycloak server that can be used for login and token refresh. By doing so the client do not need to know / access the KeyCloak server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/819)
=> Login endpoint on server

prepare-release/prepare-release.sh
This script should help to prepare a release for the dolphin-platform.
```
Dolphin Platform Release preparation v1.0.0 (2018-02-15)
No arguments supplied.
Usage: prepare-release <package> <version> [candidate]
package:      The package that should be released. Possible packages are: javascript, js-frameworks, java-examples, java
version:      The release version number in the format major.minor.patch, e.g. 1.0.0
candidate:    Optional release candidate number, e.g 4
Full Exxample:  ./prepare-release javascript 1.0.0 4
Will release javascript and frameworks as 1.0.0-CR.4 and java as 1.0.0.CR4
This script expects the packages to be found as subdirectories (git projects) relative to this script
- javascript       dolphin-platform-js
- js-frameworks    dolphin-platform-polymer, …
```
=> Prepare release script

services/keycloak/ansible/default-client.json, services/keycloak/ansible/default-user.json
Keyclock configuration updated
Public access is enabled now
User is now "user" with password "password".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/880)
=> Keyclock configuration updated

platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/property/ObservableListBean.java, platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/property/PropertyTestConstants.java, platform-integration-tests/integration-server/src/main/java/com/canoo/dolphin/integration/server/property/ObservableListController.java, platform-integration-tests/integration-server/src/test/java/com/canoo/dolphin/integration/server/property/ObservableListControllerTest.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/collections/ObservableArrayList.java
Currently the Change-Event implementation for observable lists do not allow to delete more than 1 element in a change. Based on this constrain the PR contains a workaround for handling delete(from, to).
A real solution should come with https://github.com/canoo/dolphin-platform/issues/103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/902)
=> Workaround for delete(from, to)

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/legacy/communication/CommandConstants.java
…use javascript client having "DeletePresentationModel" id for DeletePresentationModelCommand
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/907)
=> Javascript client unable to parse DeletePresentationModelCommand
