java-core/src/main/java/com/canoo/dolphin/impl/InternalAttributesBean.java
Model isn't available on Java client
=> bugfix for 0.7 release

java-client/src/test/java/com/canoo/dolphin/client/impl/TestObservableArrayListWriteOperations.java, java-core/src/main/java/com/canoo/dolphin/collections/ObservableList.java, java-core/src/main/java/com/canoo/dolphin/impl/collections/ObservableArrayList.java, java-server/src/test/java/com/canoo/dolphin/server/impl/TestObservableArrayListWriteOperations.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/12)
=> Some additional methods for the ObservableList

java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/AbstractFXMLViewBinder.java, java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/AbstractViewBinder.java, java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/JavaFXConfiguration.java, java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java, java-client/src/main/java/com/canoo/dolphin/client/ClientInitializationException.java, java-client/src/main/java/com/canoo/dolphin/client/ClientShutdownException.java, java-client/src/main/java/com/canoo/dolphin/client/State.java, java-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java
This merge requests add some convenience classes (like DolphinPlatformApplication) to the JavaFX client API and solves some problems in the creation and destruction of controller proxies and the client context
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/13)
=> JavaFX Client & Controller handling

todo-example/client/pom.xml, todo-example/common/pom.xml, todo-example/server-javaee/pom.xml, todo-example/server-spring/pom.xml, todo-example/server/pom.xml
added some Maven config
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/89)
=> ToDo Example should not be deployed to maven

java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java
Bugfix for #78
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/79)
=> Controller scan for JBOSS based on JBOSS virtual file system (VFS)

java-client/src/test/java/com/canoo/dolphin/client/TestDeleteAll.java, java-client/src/test/java/com/canoo/dolphin/client/TestModelDeletion.java, java-client/src/test/java/com/canoo/dolphin/client/TestObservableListSync.java, java-core/src/main/java/com/canoo/dolphin/impl/EventDispatcherImpl.java, java-core/src/main/java/com/canoo/dolphin/impl/PlatformConstants.java, java-core/src/main/java/com/canoo/dolphin/impl/collections/ListMapperImpl.java, java-core/src/main/java/com/canoo/dolphin/impl/collections/ObservableArrayList.java, java-core/src/main/java/com/canoo/dolphin/internal/EventDispatcher.java, java-server/src/test/java/com/canoo/dolphin/server/TestObservableListSync.java
This is an implementation for #51 
In our project it reduces the amount of data transferred between server and client by 20%.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/91)
=> Improved list ops

java-core/src/main/java/com/canoo/dolphin/impl/collections/ObservableArrayList.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/100)
=> Fix for broken list change event

java-client/src/main/java/com/canoo/dolphin/client/ClientContextFactory.java, java-core/pom.xml, java-core/src/main/java/com/canoo/dolphin/impl/codec/CommandConstants.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/CommandEncoder.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/CreatePresentationModelEncoder.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/ValueChangedCommandEncoder.java, java-core/src/test/java/com/canoo/dolphin/impl/codec/TestOptimizedJsonCodec.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/101)
=> Optimized codec

java-core/src/main/java/com/canoo/dolphin/impl/codec/CommandConstants.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/CommandEncoder.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/CreatePresentationModelEncoder.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/ValueChangedCommandEncoder.java, java-core/src/main/java/com/canoo/dolphin/impl/codec/ValueEncoder.java, java-core/src/main/java/com/canoo/dolphin/impl/collections/ListMapperImpl.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/102)
=> Fix for broken list operations

java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/JavaFXListBinder.java, java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/impl/DefaultJavaFXListBinder.java, java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/impl/BidirectionalListBinderTest.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/114)
=> Implemented initial version of bidirectional list binding

java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/AbstractFXMLViewBinder.java, java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/AbstractViewBinder.java, java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FxmlLoadException.java
This changes are based on some use cases.
Added some JavaDoc
Classes are more easy to use.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/119)
=> JavaFX basic view: some refactoring

java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/ClientScopeContext.java, java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/DolphinPlatformJavaeeBootstrap.java, java-server-spring/src/main/java/com/canoo/dolphin/server/spring/ClientScope.java, java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactory.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextProvider.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinSessionImpl.java, java-server/src/main/java/com/canoo/dolphin/server/context/DolphinSessionProvider.java, java-server/src/test/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImplMock.java
Some minor changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/129)
=> Minor changes for 0.8.3

java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/DolphinPlatformJavaeeBootstrap.java, java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, java-server/src/main/java/com/canoo/dolphin/server/config/ConfigurationFileLoader.java, java-server/src/main/java/com/canoo/dolphin/server/config/DolphinPlatformConfiguration.java, java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java, java-server/src/test/java/com/canoo/dolphin/server/config/ConfigurationFileLoaderTest.java, java-server/src/test/java/com/canoo/dolphin/server/config/DolphinPlatformConfigurationTest.java, java-server/src/test/resources/META-INF/dolphin.properties, todo-example/server-spring/src/main/resources/META-INF/dolphin.properties
Defines Configuration class for the server
config can be changed in dolphin.properties file
Default values for properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/134)
=> Server configuration

documentation/src/docs/asciidoc/model.adoc, documentation/src/docs/asciidoc/server-configuration.adoc, java-server/src/main/java/com/canoo/dolphin/server/config/ConfigurationFileLoader.java, todo-example/server-javaee/src/main/resources/META-INF/dolphin.properties, todo-example/server-kumuluzee/src/main/resources/META-INF/dolphin.properties
Updated the docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/147)
=> New Documentation for features in 0.8.4

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ClassRepositoryImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/DolphinUtils.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/mapping/MappingException.java
Currently this ends in a NPE and the cause is very hard to find...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/160)
=> Throw better exception if generic type can't be defined

platform-examples/todo-example/todo-server-spring/src/main/resources/application.properties, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextCleaner.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerHandler.java
Some quick fixes & Logging based on Test for the 0.8.5 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/174)
=> Quickfixes & Logging

platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/ClientScope.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/ClientScoped.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformApplication.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringBeanFactory.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringContainerManager.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringModelInjector.java, platform/dolphin-platform-server-spring/src/main/resources/banner.txt, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerCreationException.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerHandler.java
Logging when a new controller is created on the server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/192)
=> additional logging for controller creation

platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringBeanFactory.java
see #190
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/191)
=> provide Spring client scope with static method

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerHandler.java
See #183 for description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/184)
=> remove root model when controller is destroyed

platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java
init() method is called on Platform thread
Application will close on exit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/180)
=> some bugfixes in JavaFX threading

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientContextFactory.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java
HttpClient must be provided by Config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/199)
=> HttpClient in Config

platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextFilter.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/servlet/CrossSiteOriginFilter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/204)
=> Some minor fixes

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/AbstractBeanBuilder.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/AbstractPresentationModelBuilder.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/BeanManagerImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ClassRepositoryImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/EventDispatcherImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/InternalAttributesBean.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java
Added some null checks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/224)
=> Additional null checks

.travis.yml, README.md
Publish Ascii-Doc files to github pages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/230)
=> publish doc with travis

documentation/dolphin-platform-documentation/src/docs/asciidoc/server-configuration.adoc, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/bootstrap/DolphinPlatformBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/ConfigurationFileLoader.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/DolphinPlatformConfiguration.java
provides a new property for dolphin.properties file to deactivate MBean support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/220)
=> Activate / Deactivate MBean support by property

platform-examples/todo-example/todo-server-kumuluzee/todo-server-kumuluzee.gradle, platform/dolphin-platform-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/CdiBeanFactory.java, platform/dolphin-platform-server-javaee/src/main/resources/META-INF/beans.xml
Some small changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/225)
=> Small changes for CDI

platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/view/AbstractViewBinder.java
Exception in JavaFX client init method will not handled / catched.
See #229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/251)
=> bugfix for #229

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextFilter.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerHandler.java
Based on some exceptions that happened in customer projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/257)
=> Some additional asserts

platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/DummyUiThreadHandler.java, platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinPlatformHttpClientConnector.java, platform/dolphin-platform-core/src/test/java/com/canoo/dolphin/impl/ConverterTest.java, remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/ClientConnector.java, remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/CommandBatcherQueue.java, remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/DataflowQueue.java, remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.groovy
Some additional test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/259)
=> Converter test

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ClassRepositoryImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converter.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/info/ClassPropertyInfo.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/internal/info/PropertyInfo.java, platform/dolphin-platform-core/src/test/java/com/canoo/dolphin/impl/ConverterTest.java, remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy
This PR fixes a problem with the scope of @Log in in the AbstractClientConnector class and externalizes the Converter interface as a first step for #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/260)
=> Fix for logging in ClientConnector and externalized Converter interface

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java
Some minor changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/268)
=> some logging and better exception handling for OptimizedJsonCodec

documentation/dolphin-platform-documentation/src/docs/asciidoc/release.adoc
added step by step documentation for releases of the JS repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/278)
=> JavaScript release documentation

platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateConverterFactory.java, platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/ValueFieldTypes.java, platform-extras/dolphin-platform-date-time-converter/src/main/resources/META-INF/services/com.canoo.dolphin.converter.ConverterFactory, platform-extras/dolphin-platform-date-time-converter/src/test/java/com/canoo/dolphin/converters/LocalDateConverterFactoryTest.java
This pull request adds a Dolphin Platform Converter for the Java 8 Date and Time (JSR-310) LocalDate class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/285)
=> Add JSR-310 LocalDate Converter

.travis.yml, build.gradle
Sonar is used (see https://sonarqube.com/dashboard/index?id=com.canoo.dolphin-platform%3Adolphin-platform)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/282)
=> Sonar integration

.travis.yml, build.gradle, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinTestClientConnector.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/HttpClientMock.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/DolphinRuntimeException.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanManagerImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/IdBasedResponseHandler.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/BeanManager.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/BeanManagerImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ClassRepositoryImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/InternalAttributesBean.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/bootstrap/DolphinPlatformBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/ConfigurationFileLoader.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextUtils.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinHttpSessionListener.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollector.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/MBeanRegistry.java, remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.java
see https://sonarqube.com/component_issues/index?id=com.canoo.dolphin-platform%3Adolphin-platform#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/283)
=> [WIP] small changes based on sonar issues

documentation/dolphin-platform-documentation/src/docs/asciidoc/controller.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/event-bus.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/javaee-integration.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/javafx-client.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/jumpstart.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/lifecycle.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/model.adoc, documentation/dolphin-platform-documentation/src/docs/asciidoc/server-configuration.adoc
As discussed with Hendrik.
I also attached a small chat application which uses Dolphin's event bus - in case you'd like to use it for the doc as a simple complete example:
[Dolphin-chat.zip](https://github.com/canoo/dolphin-platform/files/674361/Dolphin-chat.zip)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/291)
=> Updated code examples of the documentation, fixed some typos.

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientContext.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ControllerProxy.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyImpl.java
Some additional  methods that are needed for android client or projectors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/304)
=> Some additional methods in Client API

documentation/src/docs/asciidoc/server-configuration.adoc, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/DolphinPlatformConfiguration.java
See #323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/324)
=> Default mapping for clientIdFilter changed to “/dolphin”

remoting/dolphin-remoting-shared/src/test/groovy/org/opendolphin/core/comm/JsonCodecTest.groovy
see https://github.com/canoo/dolphin-platform/issues/327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/328)
=> fix for issue 327

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/converters/DolphinBeanConverterFactory.java
Improve error messages while converting to dolphin bean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/336)
=> Improve error messages

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/343)
=> Remove exception from warning

documentation/src/docs/asciidoc/security.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/346)
=> Add details in document for security implementation for JS based client

remoting/dolphin-remoting-server/src/main/java/org/opendolphin/core/server/action/StoreValueChangeAction.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/351)
=> Fix NPE in StoreValueChangeAction

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/ConfigurationFileLoader.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/363)
=> Change error to info

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/bootstrap/DolphinPlatformBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/DolphinPlatformConfiguration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/368)
=> Add logging about the configuration on server

integration-tests/src/test/java/com/canoo/dolphin/integration/TodoAppTest.java, platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoView.java, platform-examples/todo-example/todo-common/src/main/java/com/canoo/dolphin/todo/TodoAppConstants.java, platform-examples/todo-example/todo-common/src/main/java/com/canoo/dolphin/todo/pm/ToDoItem.java, platform-examples/todo-example/todo-server-spring/src/main/java/com/canoo/dolphin/todo/server/ToDoServer.java, platform-examples/todo-example/todo-server-spring/src/main/java/com/canoo/dolphin/todo/server/ToDoServerConfiguration.java, platform-examples/todo-example/todo-server-spring/src/test/java/com/canoo/dolphin/todo/server/ToDoControllerTests.java, platform-examples/todo-example/todo-server-spring/todo-server-spring.gradle, platform-examples/todo-example/todo-server/src/main/java/com/canoo/dolphin/todo/server/ToDoController.java
some controller tests for the todo sample
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/365)
=> Todo sample tests

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/DolphinPlatformHttpClientConnector.java
fix #371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/373)
=> set strict mode always to false

platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/AbstractSpringContainerManager.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/bootstrap/DolphinPlatformBootstrap.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/386)
=> Fix : No qualifying bean of type DolphinListener

README.md, documentation/src/docs/asciidoc/changelog.adoc, documentation/src/docs/asciidoc/event-bus.adoc, documentation/src/docs/asciidoc/release.adoc
Additional documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/379)
=> Documentation: Release & distributed event bus

gradle.properties
based on the new Major / Minor releases we need to change the snapshot version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/383)
=> 1.0.0-SNAPSHOT

documentation/src/docs/asciidoc/server-configuration.adoc, documentation/src/docs/asciidoc/spring-integration.adoc, platform/dolphin-platform-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/DolphinPlatformJavaeeBootstrap.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformProperties.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/config/DolphinPlatformConfiguration.java
This is very useable to speed up tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/391)
=> flag to deactivate the DP bootstrap

platform-examples/process-monitor-sample/process-monitor-server/src/main/java/com/canoo/dolphin/todo/server/ProcessMonitorController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/393)
=> Fixed: Missing sessionExecutor initialization

platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/mapping/DolphinBean.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/DolphinController.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/DolphinListener.java
Adding the @Inherited annotate to some annotation to provide features for sub classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/394)
=> Add @Inherited were it makes sense

build.gradle
Link between the javadoc of the DP modules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/401)
=> Added several links for JavaDoc

platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java
Config can be provided as managed bean in Spring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/410)
=> injectable config

platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/DolphinControllerTest.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/bootstrap/DolphinPlatformBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DefaultDolphinContextFactory.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerValidationException.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerValidator.java, platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/context/DolphinContextTest.java, platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/controller/ControllerRepositoryTest.java, platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/controller/ControllerValidatorTest.java, platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/controller/TestBean.java, platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/controller/TestController.java
Add ControllerValidator to validate controller rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/412)
=> Controller validation

integration-common/gradle.properties, integration-common/src/main/java/com/canoo/dolphin/integration/property/PropertyTestBean.java, integration-common/src/main/java/com/canoo/dolphin/integration/property/PropertyTestConstants.java, integration-server/gradle.properties, integration-server/src/main/java/com/canoo/dolphin/integration/server/property/PropertyTestController.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/property/PropertyTestControllerTest.java, integration-tests-jee/gradle.properties, integration-tests/src/test/java/com/canoo/dolphin/integration/PropertyControllerTest.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java, remoting/dolphin-remoting-shared/src/test/groovy/org/opendolphin/core/BaseAttributeSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/418)
=> Number properties onChange not working 

platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateConverterFactory.java, platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java, platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/ZonedDateTimeConverterFactory.java, platform-extras/dolphin-platform-date-time-converter/src/test/java/com/canoo/dolphin/converters/ZonedDateTimeConverterFactoryTest.java, platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PlatformConstants.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/432)
=> Add Java 8 date&time support for JavaScript client

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyImpl.java
just a exception message :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/440)
=> Exception message

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextTaskQueue.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/450)
=> TaskQueue refactoring

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerHandler.java
Fix for https://github.com/canoo/dolphin-platform/issues/447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/448)
=> print action name on error

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/DolphinPlatformHttpClientConnector.java
Bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/457)
=> Bugfix for JFX connection

remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/BlindCommandBatcher.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/ClientResponseHandler.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/SimpleExceptionHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/458)
=> Replace log4j with slf4j

platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/DolphinPlatformHttpClientConnector.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/HttpClientCookieHandler.java
externalized Cookie handling in separate class
Logging for Cookie Handling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/460)
=> Logging for Cookie Handling

integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java, platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientContextFactory.java
Fix #445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/465)
=> ClientContextFactory not connect automatically

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/controller/ControllerValidator.java, platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/controller/ControllerValidatorTest.java
The validation checks for @Param now in all annotations of a method param.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/464)
=> Param annotation bugfix

platform-extras/dolphin-platform-distributed-eventbus/gradle.properties
distributed event bus added to release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/472)
=> release the jar

platform-extras/dolphin-platform-distributed-eventbus/src/main/java/com/canoo/dolphin/server/event/DefaultHazelcastProvider.java, platform-extras/dolphin-platform-distributed-eventbus/src/main/java/com/canoo/dolphin/server/event/DistributedEventBus.java, platform-extras/dolphin-platform-distributed-eventbus/src/main/java/com/canoo/dolphin/server/event/DistributedEventBusProvider.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/bootstrap/DolphinPlatformBootstrap.java
Logging for the event bus configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/473)
=> Additional logging for Distributed event bus

platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java
property can now configured by spring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/471)
=> events type property added for spring config

integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java, platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientContextFactory.java
Fix #466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/467)
=> ClientContextFactory do not return a promise

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/CommunicationManager.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextTaskQueue.java, remoting/dolphin-remoting-server/src/main/java/org/opendolphin/core/server/ServerModelStore.java
TaskExecutor returns if the server wants to send any commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/469)
=> WiP: Check in task executor for commands

gradle.properties, integration-server/src/test/java/com/canoo/dolphin/integration/server/action/ActionTestControllerTest.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/enterprise/EnterpriseTestControllerTest.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/property/PropertyTestControllerTest.java, platform-examples/todo-example/todo-server-spring/src/test/java/com/canoo/dolphin/todo/server/ToDoControllerTests.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringTestNGControllerTest.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/DolphinControllerTest.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/JUnitDemoTest.java, platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/scopes/ScopeTestControllerTest.java, platform/dolphin-platform-server-spring/dolphin-platform-server-spring.gradle, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformApplication.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dolphin/server/spring/SpringContainerManager.java
Changes Spring-Boot dependency to 1.5.3.RELEASE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/492)
=> Update to Spring-Boot 1.5.3

platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinTestClientConnector.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/ClientContext.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/DolphinPlatformHttpClientConnector.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/AbstractClientConnector.java, remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, remoting/dolphin-remoting-combined/src/main/java/core/client/comm/InMemoryClientConnector.java
See issue https://github.com/canoo/dolphin-platform/issues/490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/491)
=> client id provided by clientContext

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/event/ListEventSessionFilter.java
ListEventSessionFilter added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/487)
=> ListEventSessionFilter added

documentation/src/docs/asciidoc/validation.adoc
Fixes a minor typo in the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/507)
=> Fixes #505

documentation/src/docs/asciidoc/validation.adoc
Done
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/506)
=> Link added

platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/event/AbstractEventBus.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/event/DolphinEvent.java
Fix for #523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/524)
=> filter events for all sessions

platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/event/impl/AbstractEventBus.java, platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEvent.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/525)
=> filter events for all sessions bugfix

platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/event/AbstractEventBus.java, platform/dolphin-platform-rpm-server/src/test/java/com/canoo/impl/server/event/DefaultDolphinEventBusTest.java
Fix for https://github.com/canoo/dolphin-platform/issues/534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/535)
=> BugFix: publishing on EventBus outside session

integration-common/src/main/java/com/canoo/dolphin/integration/action/ActionTestConstants.java, integration-server/src/main/java/com/canoo/dolphin/integration/server/action/ActionTestController.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/action/ActionTestControllerTest.java, integration-tests/src/test/java/com/canoo/dolphin/integration/ActionControllerTest.java, platform/dolphin-platform-core/src/main/java/com/canoo/impl/platform/core/ReflectionHelper.java, platform/dolphin-platform-core/src/test/java/com/canoo/impl/platform/core/ReflectionHelperTest.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/JsonNumberUtils.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/ValueEncoder.java, platform/dolphin-platform-rpm-common/src/test/java/com/canoo/dolphin/impl/codec/TestOptimizedJsonCodec.java, platform/dolphin-platform-rpm-common/src/test/java/com/canoo/dolphin/impl/codec/encoders/ValueEncoderTest.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java
Bugfix for null values and numbers ac action params
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/543)
=> Null param fix

platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dp/impl/client/DolphinPlatformHttpClientConnector.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/ValueChangedCommandEncoder.java, platform/dolphin-platform-rpm-common/src/test/java/com/canoo/dolphin/impl/codec/TestOptimizedJsonCodec.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/DefaultModelSynchronizer.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/AbstractClientConnector.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/BlindCommandBatcher.java, remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/ClientResponseHandler.java, remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.java, remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/CommunicationTests.java, remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/FunctionalPresentationModelTests.groovy, remoting/dolphin-remoting-server/src/main/java/org/opendolphin/core/server/ServerModelStore.java, remoting/dolphin-remoting-server/src/main/java/org/opendolphin/core/server/action/StoreValueChangeAction.java, remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/JsonCodec.java, remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/ValueChangedCommand.java, remoting/dolphin-remoting-shared/src/test/groovy/org/opendolphin/core/comm/JsonCodecTest.groovy
This can not be merged before JS part is ready!
Fix for https://github.com/canoo/dolphin-platform/issues/529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/537)
=> WIP: OldValue of ValueChangedCommand removed

platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/CommandConstants.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CreateContextCommandEncoder.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/DestroyContextCommandEncoder.java
shorter communication protocol for context based commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/547)
=> bugfix for context commands

.travis.yml, integration-common/src/main/java/com/canoo/dolphin/integration/enterprise/EnterpriseTestBean.java, integration-server/integration-server.gradle, integration-server/src/main/java/com/canoo/dolphin/integration/server/enterprise/EnterpriseTestController.java, integration-server/src/main/java/com/canoo/dolphin/integration/server/listener/TestClientSessionListener.java, integration-server/src/main/java/com/canoo/dolphin/integration/server/property/PropertyTestController.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/enterprise/EnterpriseTestControllerTest.java, integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java, platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/ValueChangedCommandEncoder.java, platform/dolphin-platform-server-javaee/src/main/java/com/canoo/dp/impl/server/javaee/CdiBeanFactory.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dp/impl/server/spring/SpringBeanFactory.java
Provides a proxy for the eventbus to provide injection before DP has been full booted.
Some small changes for integration tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/555)
=> EventBus Proxy

platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/event/LazyEventBusInvocationHandler.java, platform/dolphin-platform-server-javaee/src/main/java/com/canoo/dp/impl/server/javaee/CdiBeanFactory.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/dp/impl/server/spring/SpringBeanFactory.java
Added LazyEventBusInvocationHandler class for lazy event bus support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/558)
=> LazyEventBusInvocationHandler for eventBus proxy

platform/dolphin-platform-core/src/main/java/com/canoo/impl/platform/core/ReflectionHelper.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java
Better error messages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/561)
=> error message for action error

platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContextCommunicationHandler.java
Fix NPE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/560)
=> fix NPE in LazyEventBus

platform/dolphin-platform-core/src/main/java/com/canoo/impl/platform/core/ReflectionHelper.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/562)
=> error message

platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContext.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java
fix for bean params
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/564)
=> Fix for bean params

platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dp/impl/client/ControllerProxyFactoryImpl.java, platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dp/impl/client/ControllerProxyImpl.java
convert client params for action call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/565)
=> client param convert

platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/RemotingContextImpl.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/RemotingContext.java
see #552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/568)
=> RemotingContext.getClientSession() added

integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java, platform/dolphin-platform-core/src/main/java/com/canoo/impl/platform/core/PlatformConstants.java, platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dp/impl/client/DolphinPlatformHttpClientConnector.java
Fix for encoding in JavaEE
faster integration tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/567)
=> encoding fix for JavaEE server with Java client

platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/impl/dp/spring/test/DolphinPlatformSpringTestBootstrap.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/impl/dp/spring/test/DolphinTestContext.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/impl/dp/spring/test/TestConfiguration.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/event/AbstractEventBus.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/event/EventSessionFilterFactory.java, platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/event/ListEventSessionFilter.java, platform/dolphin-platform-rpm-server/src/test/java/com/canoo/impl/server/context/DolphinContextTest.java, platform/dolphin-platform-rpm-server/src/test/java/com/canoo/impl/server/event/DefaultDolphinEventBusTest.java, platform/dolphin-platform-rpm-server/src/test/java/com/canoo/impl/server/util/HttpSessionMock.java, platform/dolphin-platform-server/src/main/java/com/canoo/impl/server/client/ClientSessionManager.java, platform/dolphin-platform-server/src/main/java/com/canoo/impl/server/client/HttpClientSessionImpl.java, platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/client/ClientSession.java, platform/dolphin-platform-server/src/test/java/com/canoo/impl/server/ClientSessionImplTest.java, platform/dolphin-platform-server/src/test/java/com/canoo/impl/server/util/HttpSessionMock.java
Some more functionality for event filtering
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/575)
=> better API for session filters

integration-common/src/main/java/com/canoo/dolphin/integration/bean/BeanTestBean.java, integration-common/src/main/java/com/canoo/dolphin/integration/bean/BeanTestConstants.java, integration-server/src/main/java/com/canoo/dolphin/integration/server/beans/BeanTestController.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/beans/BeanTestControllerTest.java, integration-tests/src/test/java/com/canoo/dolphin/integration/BeansControllerTest.java, platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/impl/dp/spring/test/DolphinPlatformSpringTestBootstrap.java
Adds support to inject RemotingContext in tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/582)
=> RemotingContext injection in test

platform/dolphin-platform-server-spring/src/main/java/com/canoo/platform/server/spring/ClientScope.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/platform/server/spring/PrototypeScope.java, platform/dolphin-platform-server-spring/src/main/java/com/canoo/platform/server/spring/SingletonScope.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/597)
=> Spring scope defitions

integration-common/src/main/java/com/canoo/dolphin/integration/action/ActionTestBean.java, integration-common/src/main/java/com/canoo/dolphin/integration/action/ActionTestConstants.java, integration-server/src/main/java/com/canoo/dolphin/integration/server/action/ActionTestController.java, integration-server/src/test/java/com/canoo/dolphin/integration/server/action/ActionTestControllerTest.java, integration-tests/src/test/java/com/canoo/dolphin/integration/ActionControllerTest.java
Added unit and integration test for other supported data type test in ActionTestController
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/599)
=> Added test for other supported data type test in ActionTestController

integration-tests/src/test/java/com/canoo/dolphin/integration/ActionControllerTest.java
Make ActionTestController test not changing variable as final.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/600)
=> ActionTestController Test

platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/ClientContextImpl.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/DolphinPlatformHttpClientConnector.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/legacy/communication/AbstractClientConnector.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/legacy/communication/SimpleExceptionHandler.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/platform/remoting/client/ClientConfiguration.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/platform/remoting/client/ClientContextFactory.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/platform/remoting/client/RemotingExceptionHandler.java, platform/dolphin-platform-remoting-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinPlatformHttpClientConnector.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/DolphinRemotingException.java
Remoting exception handler added to public API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/615)
=> Exception handler to public API

integration-tests/src/test/java/com/canoo/dolphin/integration/ClientIdTest.java, platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/ClientSessionSupport.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/DolphinPlatformHttpClientConnector.java
Bugfix for clientContext.getClientId()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/616)
=> Return client ID

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/collections/ObservableArrayList.java, platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/collections/TestObservableArrayList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/637)
=> Implement observable list remove all and retain all

platform-extras/dolphin-platform-reactive/src/main/java/com/canoo/dp/impl/reactive/TransformedPropertyImpl.java, platform-extras/dolphin-platform-reactive/src/main/java/com/canoo/platform/reactive/ReactiveTransormations.java, platform-extras/dolphin-platform-reactive/src/main/java/com/canoo/platform/reactive/TransformedProperty.java, platform-extras/dolphin-platform-reactive/src/test/java/com/canoo/platform/reactive/ReactiveTransormationsDemo.java
Refactored classes of reactive module to public/private packages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/640)
=> Refactored classes of reactive module to public/private packages

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerHandler.java
Hi, it's for ticket https://github.com/canoo/dolphin-platform/issues/641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/642)
=> Fix for @ParentController annotation is not working

gradle.properties, platform/dolphin-platform-remoting-server-javaee/dolphin-platform-remoting-server-javaee.gradle, platform/dolphin-platform-server-javaee/dolphin-platform-server-javaee.gradle
deltaSpikeVersion=1.8.0
gsonVersion=2.8.2
guavaVersion=23.2-jre
jacocoVersion=0.7.9
jmockitVersion=1.35
rxjavaVersion=1.3.2
slf4jVersion=1.8.0-alpha2
springBootVersion=1.5.6.RELEASE
add property for cdiApiVersion
Fixes #515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/644)
=> Update of all library dependencies

platform/dolphin-platform-client/src/test/java/com/canoo/dp/impl/platform/client/session/SimpleUrlToAppDomainConverterTest.java
Hi!
Creating a unit test as requested
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/700)
=> Provide unit tests for SimpleUrlToAppDomainConverter #696

platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/IdentitySet.java, platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/IdentitySetTest.java
Did not add a lot of tests because there were already some, but caught a bug and fixed it.
add method was not returning correct boolean - had to add an "!".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/699)
=> FIXed: IdentitySet

platform-extras/dolphin-platform-bean-validation/src/main/java/com/canoo/dp/impl/validation/DigitsPropertyValidator.java, platform-extras/dolphin-platform-bean-validation/src/main/resources/META-INF/mapping/validationMappingDolphinPlatform.xml, platform-extras/dolphin-platform-bean-validation/src/test/java/com/canoo/dp/impl/validation/ValidationTest.java
These changes fix #654 . Please have a look and let me know if anythings needs to be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/679)
=> #654 added DigitsPropertyValidator and Testcase

platform/dolphin-platform-client/src/test/java/com/canoo/dp/impl/platform/client/session/ClientSessionStoreImplTest.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/703)
=> provide unit tests for ClientSessionStoreImpl

platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/collections/TestObservableArrayList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/667)
=> ObservableList: Improve addAll and removeAll tests

platform-integration-tests/integration-tests/src/test/java/com/canoo/dolphin/integration/IntegrationTestToolkit.java, platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/HeadlessToolkit.java, platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/Toolkit.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/FxToolkit.java
See https://github.com/canoo/dolphin-platform/issues/693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/722)
=> add name to toolkit

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/collections/ObservableArrayList.java, platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/collections/TestObservableArrayList.java
Observable List modification via sublist and vice versa.  (#61)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/721)
=> Observable List Modification Via Sublist

platform/dolphin-platform-distributed-eventbus/src/main/java/com/canoo/dp/impl/server/event/DefaultHazelcastProvider.java, platform/dolphin-platform-distributed-eventbus/src/main/java/com/canoo/dp/impl/server/event/DistributedEventBusConfigProvider.java, platform/dolphin-platform-distributed-eventbus/src/main/java/com/canoo/dp/impl/server/event/HazelcastConfig.java
some params to define connection timeouts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/724)
=> additional hazelcast params

platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/http/HttpStatus.java
addes some http status flags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/727)
=> addes some http status flags

gradle.properties, platform-extras/dolphin-platform-logger/dolphin-platform-logger.gradle, platform-extras/dolphin-platform-logger/gradle.properties, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/core/ClasspathScanner.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/core/DefaultHttpURLConnectionFactory.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/core/HttpConstants.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/DolphinLogger.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/DolphinLoggerConfiguration.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/DolphinLoggerFactory.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/DolphinLoggerUtils.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/bridges/GelfMessage.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/bridges/RemoteLogger.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/bridges/RemoteLoggerFactory.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/bridges/SimpleDolphinLogger.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/bridges/SimpleDolphinLoggerFactory.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/impl/DolphinLoggerThreadFactory.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/impl/LogMessage.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/impl/ThreadLocalMDCAdapter.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/sample/Sample.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/spi/DolphinLoggerBridge.java, platform-extras/dolphin-platform-logger/src/main/java/com/canoo/dolphin/logger/spi/DolphinLoggerBridgeFactory.java, platform-extras/dolphin-platform-logger/src/main/java/org/slf4j/impl/StaticLoggerBinder.java, platform-extras/dolphin-platform-logger/src/main/java/org/slf4j/impl/StaticMDCBinder.java, platform-extras/dolphin-platform-logger/src/main/java/org/slf4j/impl/StaticMarkerBinder.java, platform-extras/dolphin-platform-logger/src/main/resources/META-INF/services/com.canoo.dolphin.logger.spi.DolphinLoggerBridgeFactory, settings.gradle
First commit of the logger API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/725)
=> WIP: DP Logger API

platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/DefaultClientConfiguration.java, platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/config/ConfigurationFileLoader.java, platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/PlatformClient.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/config/ConfigurationFileLoader.java
Added loader for client config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/728)
=> client config can be defined on file

platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/scanner/DefaultClasspathScanner.java
Bugfix for #734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/735)
=> Added new config param to reflections configuration

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/collections/ObservableArrayList.java, platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/collections/TestObservableArrayList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/739)
=> Fixed retain all issue

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/AbstractBeanBuilder.java
some logging that helps to understand a runtime error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/745)
=> additional logging for bean creation errors

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/collections/ObservableArrayList.java, platform/dolphin-platform-remoting-common/src/test/java/com/canoo/dolphin/impl/collections/TestObservableArrayList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/744)
=> Implement ObservableList modifications via list iterator

platform-examples/lazy-loading-sample/lazy-loading-client-javafx/lazy-loading-client-javafx.gradle, platform-examples/lazy-loading-sample/lazy-loading-client-javafx/src/main/java/com/canoo/platform/samples/lazyloading/Client.java, platform-examples/lazy-loading-sample/lazy-loading-client-javafx/src/main/java/com/canoo/platform/samples/lazyloading/View.java, platform-examples/lazy-loading-sample/lazy-loading-common/lazy-loading-common.gradle, platform-examples/lazy-loading-sample/lazy-loading-common/src/main/java/com/canoo/platform/samples/lazyloading/Constants.java, platform-examples/lazy-loading-sample/lazy-loading-common/src/main/java/com/canoo/platform/samples/lazyloading/LazyLoadingBean.java, platform-examples/lazy-loading-sample/lazy-loading-common/src/main/java/com/canoo/platform/samples/lazyloading/LazyLoadingItem.java, platform-examples/lazy-loading-sample/lazy-loading-server-spring/lazy-loading-server-spring.gradle, platform-examples/lazy-loading-sample/lazy-loading-server-spring/src/main/java/com/canoo/platform/samples/lazyloading/LazyLoadingController.java, platform-examples/lazy-loading-sample/lazy-loading-server-spring/src/main/java/com/canoo/platform/samples/lazyloading/Server.java, settings.gradle
Added a sample that shows Lazy Loading functionality
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/753)
=> Lazy Loading sample added

platform-examples/microservices-sample/microservice-client/gradle.properties, platform-examples/microservices-sample/microservice-client/microservice-client.gradle, platform-examples/microservices-sample/microservice-client/src/main/java/com/canoo/platform/samples/microservices/Client.java, platform-examples/microservices-sample/microservice-product-common/microservice-product-common.gradle, platform-examples/microservices-sample/microservice-product-common/src/main/java/com/canoo/platform/samples/microservices/product/ProductBean.java, platform-examples/microservices-sample/microservice-product-common/src/main/java/com/canoo/platform/samples/microservices/product/ProductConstants.java, platform-examples/microservices-sample/microservice-product-server/gradle.properties, platform-examples/microservices-sample/microservice-product-server/microservice-product-server.gradle, platform-examples/microservices-sample/microservice-product-server/src/main/java/com/canoo/platform/samples/microservices/product/ProductController.java, platform-examples/microservices-sample/microservice-product-server/src/main/java/com/canoo/platform/samples/microservices/product/ProductServer.java, platform-examples/microservices-sample/microservice-product-server/src/main/resources/application.properties, platform-examples/microservices-sample/microservice-user-common/microservice-user-common.gradle, platform-examples/microservices-sample/microservice-user-common/src/main/java/com/canoo/platform/samples/microservices/user/UserBean.java, platform-examples/microservices-sample/microservice-user-common/src/main/java/com/canoo/platform/samples/microservices/user/UserConstants.java, platform-examples/microservices-sample/microservice-user-server/gradle.properties, platform-examples/microservices-sample/microservice-user-server/microservice-user-server.gradle, platform-examples/microservices-sample/microservice-user-server/src/main/java/com/canoo/platform/samples/microservices/user/UserController.java, platform-examples/microservices-sample/microservice-user-server/src/main/java/com/canoo/platform/samples/microservices/user/UserServer.java, platform-examples/microservices-sample/microservice-user-server/src/main/resources/application.properties, settings.gradle
A client that connects to 2 servers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/752)
=> microservice sample started

.travis.yml, platform-examples/lazy-loading-sample/lazy-loading-client-javafx/gradle.properties, platform-examples/lazy-loading-sample/lazy-loading-server-spring/gradle.properties, platform-examples/microservices-sample/microservice-client/microservice-client.gradle, platform-examples/microservices-sample/microservice-product-common/gradle.properties, platform-examples/microservices-sample/microservice-product-server/microservice-product-server.gradle, platform-examples/microservices-sample/microservice-user-common/gradle.properties, platform-examples/microservices-sample/microservice-user-server/microservice-user-server.gradle, platform-integration-tests/integration-tests/docker-base/tomee-integration/Dockerfile, platform-integration-tests/integration-tests/docker-base/wildfly-integration/Dockerfile, platform-integration-tests/integration-tests/docker-compose.yml, platform-integration-tests/integration-tests/integration-tests.gradle, platform-integration-tests/integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java
Fixing docker based integration tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/770)
=> Integration test fix

platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/view/AbstractViewController.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/platform/remoting/client/ControllerActionException.java
Removed unneeded constructors from ControllerActionException
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/767)
=> Removed unneeded constructors from ControllerActionException

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/context/DolphinContextTaskQueue.java
Last SettableFuture is removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/771)
=> Changed SettableFuture to CompletableFuture

platform-extras/dolphin-platform-security-server/src/main/java/com/canoo/dp/impl/server/security/SecurityModule.java, platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/RemotingModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/PlatformBootstrap.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/ClientSessionModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/CorsModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/HttpMutexModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/HttpTimeoutModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/spi/ModuleDefinition.java, platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/spi/ServerModule.java
Fix for #742
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/773)
=> added getName() to server module

platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/DefaultClientConfiguration.java, platform/dolphin-platform-core/src/main/java/com/canoo/platform/core/PlatformConfiguration.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/config/DefaultPlatformConfiguration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/775)
=> Add getProperty method without default value

platform/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/DurationConverterFactory.java, platform/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateConverterFactory.java, platform/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java, platform/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/PeriodConverterFactory.java, platform/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/ZonedDateTimeConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/Converters.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/BigDecimalConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/BigIntegerConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/BooleanConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/ByteConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/CalendarConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/DateConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/DolphinBeanConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/DoubleConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/EnumConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/FloatConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/IntegerConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/LongConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/ShortConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/StringConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/converters/UuidConverterFactory.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/spi/converter/ConverterFactory.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/778)
=> Check for converter errors

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerHandler.java, platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerUtils.java, platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerValidator.java, platform/dolphin-platform-remoting-server/src/test/java/com/canoo/dp/impl/server/controller/ControllerValidatorTest.java, platform/dolphin-platform-remoting-server/src/test/java/com/canoo/dp/impl/server/controller/repository/ControllerRepositoryTest.java, platform/dolphin-platform-remoting-server/src/test/java/com/canoo/dp/impl/server/controller/repository/TestController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/777)
=> Change validation error messages to include action name.

platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/PlatformClient.java, platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerValidator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/786)
=> Check if toolkit is set or not

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/RemotingModule.java
https://github.com/canoo/dolphin-platform/issues/733
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/792)
=> Throw exception id configured distributed event bus is not on classpath

platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/DolphinPlatformApplication.java
https://github.com/canoo/dolphin-platform/issues/765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/791)
=> Remove Unused Exception

platform/dolphin-platform-remoting-common/dolphin-platform-remoting-common.gradle, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/BeanRepositoryImpl.java
https://github.com/canoo/dolphin-platform/issues/772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/793)
=> Replace Guava multimap with hashmap

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/event/AbstractEventBus.java
fix for https://github.com/canoo/dolphin-platform/issues/798
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/799)
=> Eventbus is publishing to other sessions

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/event/AbstractEventBus.java
Logging for Runtime exceptions in event listener
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/807)
=> Logging for Runtime exceptions in event listener

platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/AbstractProperty.java
added equals
use Objects helper methods for hashCode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/815)
=> equals & hashCode for properties

platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/scanner/DefaultClasspathScanner.java, platform/dolphin-platform-server/src/test/java/com/canoo/impl/server/ClasspathScannerTest.java, platform/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/impl/dp/spring/test/TestConfiguration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/824)
=> Configuration in test is not based on properties file

platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/PlatformClient.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/PlatformVersion.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/ansi/AnsiOut.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/ansi/PlatformLogo.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/PlatformBootstrap.java
fix for https://github.com/canoo/dolphin-platform/issues/829
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/830)
=> Print version of Dolphin Platform at boot time

platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/parentchild/ChildTestBean.java, platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/parentchild/DummyChildTestBean.java, platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/parentchild/ParentChildTestConstants.java, platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/parentchild/ParentTestBean.java, platform-integration-tests/integration-server/src/main/java/com/canoo/dolphin/integration/server/parentchild/ChildTestController.java, platform-integration-tests/integration-server/src/main/java/com/canoo/dolphin/integration/server/parentchild/DummyChildTestController.java, platform-integration-tests/integration-server/src/main/java/com/canoo/dolphin/integration/server/parentchild/ParentTestController.java, platform-integration-tests/integration-server/src/test/java/com/canoo/dolphin/integration/server/parentchild/ParentChildTestControllerTest.java, platform-integration-tests/integration-tests/src/test/java/com/canoo/dolphin/integration/ParentChildControllerTest.java, platform/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/impl/dp/spring/test/ClientTestFactory.java, platform/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/platform/spring/test/ControllerUnderTest.java, start-integration-containers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/840)
=> Controller tests for parent child

platform-extras/dolphin-platform-bean-validation-rest/dolphin-platform-bean-validation-rest.gradle, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/InvalidJsonException.java, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/RemoteConstants.java, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/RemoteValidationConfiguration.java, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/RemoteValidationServlet.java, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/impl/ConstraintsViolationSerializer.java, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/impl/DefaultValidationConfiguration.java, platform-extras/dolphin-platform-bean-validation-rest/src/main/java/com/canoo/dp/impl/validation/rest/validator/impl/RemoteValidator.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/PlatformVersion.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/ansi/PlatformLogo.java, settings.gradle
First classes of the remote validation module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/838)
=> Remote Validation

platform-extras/dolphin-platform-data-audit/dolphin-platform-data-audit.gradle, platform-extras/dolphin-platform-data-audit/src/main/java/com/canoo/dp/impl/platform/data/audit/AuditContext.java, platform-extras/dolphin-platform-data-audit/src/main/java/com/canoo/dp/impl/platform/data/audit/Auditable.java, platform-extras/dolphin-platform-data-jpa/dolphin-platform-data-jpa.gradle, platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/AbstractEntity.java, platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/SimpleCrudService.java, platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/event/PersistenceListener.java, platform-extras/dolphin-platform-data-jpa/src/main/java/com/canoo/dp/impl/platform/data/jpa/event/PersistenceListenerManager.java, platform-extras/dolphin-platform-data/dolphin-platform-data.gradle, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/CrudService.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/EntityWithId.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/i18n/I18nService.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/i18n/I18nServiceImpl.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/i18n/Utf8ResourceBundle.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/BeanConverter.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/BeanMapper.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/BeanMapperImpl.java, platform-extras/dolphin-platform-data/src/main/java/com/canoo/dp/impl/platform/data/mapping/ConversionException.java, settings.gradle
Bean - Entity mapping
general service classes
basic JPA implementations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/835)
=> 2 small extra modules that helps to handle data (like JPA)

services/README.md, services/base/Dockerfile, services/buildBase.sh, services/clearDocker.sh, services/docker-compose.yml, services/downloadArtifacts.sh, services/keycloak/Dockerfile, services/keycloak/ansible/default-client.json, services/keycloak/ansible/default-realm.json, services/keycloak/ansible/default-user.json, services/keycloak/ansible/site.yml, services/registry/Dockerfile, services/restart.sh
Docker definition to set up a keycloak for the security samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/832)
=> Docker services: Keycloak

platform-extras/dolphin-platform-security-client/src/main/java/com/canoo/dp/impl/security/KeycloakSecurity.java
Connection was created twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/843)
=> Bugfix for security http connection

platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/context/ClientSessionExecutorImpl.java
fix for https://github.com/canoo/dolphin-platform/issues/737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/844)
=> exception logging

gradle.properties, platform/dolphin-platform-client/src/main/java/com/canoo/dp/impl/platform/client/config/ConfigurationFileLoader.java, platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/PlatformClient.java, platform/dolphin-platform-core/dolphin-platform-core.gradle
- custom config supported
- guava removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/852)
=> custom config supported

platform-examples/web-deployment-example/web-deployment-client/web-deployment-client.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/863)
=> Fix web deployment jnlp issue

platform-integration-tests/integration-common/src/main/java/com/canoo/dolphin/integration/controllerwithoutmodel/ControllerWithoutModelTestConstants.java, platform-integration-tests/integration-server/src/main/java/com/canoo/dolphin/integration/server/controllerwithoutmodel/ControllerWithoutModel.java, platform-integration-tests/integration-server/src/test/java/com/canoo/dolphin/integration/server/controllerwithoutmodel/ControllerWithoutModelTest.java, platform-integration-tests/integration-tests/src/test/java/com/canoo/dolphin/integration/ControllerWithoutModelTest.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/ClientContextImpl.java, platform/dolphin-platform-remoting-client/src/main/java/com/canoo/dp/impl/client/ControllerProxyImpl.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/InternalAttributesBean.java, platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerRepository.java, platform/dolphin-platform-remoting-server/src/main/java/com/canoo/dp/impl/server/controller/ControllerValidator.java, platform/dolphin-platform-remoting-server/src/test/java/com/canoo/dp/impl/server/controller/ControllerValidatorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/862)
=> Commented mandatory model validation for a controller. 

platform-examples/distribution-sample/distribution-client/src/main/java/com/canoo/platform/samples/distribution/client/DistributionClient.java, platform-examples/simple-rest/simple-rest-client-javafx/src/main/java/com/canoo/dolphin/samples/rest/RestClient.java, platform/dolphin-platform-client-javafx/dolphin-platform-client-javafx.gradle, platform/dolphin-platform-client-javafx/gradle.properties, platform/dolphin-platform-client-javafx/src/main/java/com/canoo/platform/client/javafx/FxToolkit.java, platform/dolphin-platform-client-swing/dolphin-platform-client-swing.gradle, platform/dolphin-platform-client-swing/gradle.properties, platform/dolphin-platform-client-swing/src/main/java/com/canoo/platform/client/swing/SwingToolkit.java, platform/dolphin-platform-remoting-client-javafx/src/main/java/com/canoo/platform/remoting/client/javafx/DolphinPlatformApplication.java, settings.gradle
swing & javaFX basic client modules with UIToolkit implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/875)
=> swing & javaFX basic client modules

platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/http/URLParams.java, platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/http/URLTemplate.java, platform/dolphin-platform-core/src/test/java/com/canoo/platform/core/http/URLTemplateTests.java
Fix for https://github.com/canoo/dolphin-platform/issues/873
All classes are part of private API for the moment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/874)
=> First URLTemplate implementation for simple var replacement in URLs

platform-extras/dolphin-platform-security-server/src/main/java/com/canoo/dp/impl/server/security/KeycloakConfiguration.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/ServerCoreComponentsImpl.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/CorsModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/HttpTimeoutModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/bootstrap/modules/ServerTimingModule.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/client/ClientSessionFilter.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/client/ClientSessionLifecycleHandlerImpl.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/client/ClientSessionManager.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/client/HttpClientSessionImpl.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/client/HttpSessionCleanerListener.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/config/ConfigurationFileLoader.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/mbean/MBeanDescription.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/mbean/MBeanRegistry.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/scanner/DefaultClasspathScanner.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/servlet/CrossSiteOriginFilter.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/servlet/HttpSessionTimeoutListener.java, platform/dolphin-platform-server/src/main/java/com/canoo/dp/impl/server/servlet/ServletOutputStreamCopier.java
added final keyword and null checks in server module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/876)
=> final keywords and null checks in server module

services/.gitignore, services/buildBase.sh, services/clearDocker.sh, services/downloadArtifacts.sh, services/keycloak/Dockerfile, services/keycloak/ansible/default-user.json, services/keycloak/ansible/site.yml
Cleanup script will now remove the keycloak containers and images
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/881)
=> Cleanup script will now remove the keycloak containers and images

platform/dolphin-platform-core/src/main/java/com/canoo/dp/impl/platform/core/PlatformConstants.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/PlatformRemotingConstants.java, platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/legacy/RemotingConstants.java
Fir for https://github.com/canoo/dolphin-platform/issues/846
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/849)
=> Client session header renamed for better support

platform-extras/dolphin-platform-security-client/src/main/java/com/canoo/dp/impl/security/KeycloakSecurity.java
Encode parameters to fix issue https://github.com/canoo/dolphin-platform/issues/856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/885)
=> Encode parameters

documentation/src/docs/asciidoc/release.adoc, prepare-release/prepare-release.sh
A fix for the script and some documentation updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/886)
=> Release script fix and Documentation update

platform/dolphin-platform-client/src/test/java/com/canoo/dp/impl/platform/client/http/HttpClientTests.java
Hi!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canoo/dolphin-platform/904)
=> Add test for permanent redirects, plus some minor changes
